name: Unit Tests

# MANUAL_TRIGGER
# on:
#   pull_request:
#     branches:
#       - develop
#       - release/**
#     paths:
#       - bmtk/**
#       - .github/workflows/**
on: [repository_dispatch, workflow_dispatch]

jobs:
  # CINTENT >> UNSUPPORTED_OS
  # run-tests:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-22.04]
  #       python-version: ["3.8", "3.9", "3.10", "3.11"]

  #   steps:
  #     - uses: actions/checkout@v2
      
  #     - name: Install Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
      
  #     - name: Install Requirements
  #       run: |
  #         pip install -r test_requirements.txt
  #         pip install neuron
  #         pip install .

  #     - name: Check NRN mechanisms directory exists
  #       id: has_mechanisms_dir
  #       uses: andstor/file-existence-action@v1
  #       with:
  #         files: tests/simulator/bionet/components/mechanisms

  #     - name: Setup NEURON
  #       if: steps.has_mechanisms_dir.outputs.files_exists == 'true'
  #       run: |
  #         cd tests/simulator/bionet/components/mechanisms
  #         nrnivmodl modfiles

  #     - name: Run Tests
  #       run: |
  #         pytest --cov=bmtk --cov-report=html tests
          
  linter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3e5b2faf83a2ad32c22a1cd0f86f5f20ea53a5ab

      - name: Install Requirements
        run: |
          pip install -r test_requirements.txt

      - name: Run Python Linter
        run: |
          flake8 bmtk --exit-zero --statistics --count

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
